import type { Metadata } from "next";
import "./globals.css"
import { fraunces, inter, plexMono } from "./fonts";

export const metadata: Metadata = {
  title: "my-app",
  description: "Generated by create-prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${fraunces.variable} ${inter.variable} ${plexMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}

