import type { Metadata } from "next";
import { fraunces, inter, plexMono } from "./fonts";
import "./global.css";

export const metadata: Metadata = {
  title: "DepoT",
  description: "Generated by create-prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${fraunces.variable} ${inter.variable} ${plexMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}

